version: "3"

vars:
  PROJECT_CODE: iss_server

  # folders
  BIN_FOLDER: bin

  # build options
  # -v  print the names of packages as they are compiled
  # -s  omit the symbol table and debug information
  # -w  omit the DWARF symbol table
  #
  BUILD_OPTIONS: -v -ldflags="-s -w"

tasks:
  default:
    cmds:
      - task: list-tools
    silent: false

  build:
    env:
      GOOS: linux
      GOARCH: amd64
    vars:
      OUTPUT_FILE: "{{.BIN_FOLDER}}/{{.PROJECT_CODE}}"
    cmds:
      - go build {{.BUILD_OPTIONS}} {{.TASK_OPTIONS}} -o {{.OUTPUT_FILE}}
    internal: false

  build-windows:
    env:
      GOOS: windows
      GOARCH: amd64
    vars:
      OUTPUT_FILE: "{{.BIN_FOLDER}}/{{.PROJECT_CODE}}.exe"
    cmds:
      - go build {{.BUILD_OPTIONS}} {{.TASK_OPTIONS}} -o {{.OUTPUT_FILE}}
    internal: false

  rebuild:
    cmds:
      - task: tidy
      - task: verify
      - task: build
        vars: { TASK_OPTIONS: "-a" }
    silent: false

  tidy:
    cmds:
      - rm -rf ./bin
      - go fmt ./...
      - go mod tidy -v
    silent: false

  verify:
    cmds:
      - go mod verify
      - go vet ./...
    silent: false

  update:
    cmds:
      - go get -u all
    silent: false

  run:
    platforms: [linux/amd64]
    cmds:
      - mkdir -p log
      - rm -f log/{{.PROJECT_CODE}}*.log
      - ./bin/{{.PROJECT_CODE}} {{.CLI_ARGS}}
    silent: false

  dev:
    platforms: [linux/amd64]
    cmd: go run .
    silent: false

  list:
    cmds:
      - go list -u -m all
    silent: false

  list-tools:
    cmds:
      - go version
      - gcc --version
      - task --version
    silent: false
